#pragma once
#include <string>
#include <vector>
#include <functional>
#include <nlohmann/json.hpp>
#include "core/types.hpp"
#include "ImReflect.hpp"


namespace ChadEngine { class EngineClass; extern EngineClass Engine; }


namespace ChadEngine {


	struct ComponentEntry 
	{
		std::string name;
		std::function<bool(Entity)> hasComponent;
		std::function<void(Entity)> inspect;
		std::function<void(Entity, nlohmann::json&)> save;
		std::function<void(Entity, const nlohmann::json&)> load;
	};




	class ComponentRegistry 
	{
	public:

		static std::vector<ComponentEntry>& Pending() {
			static std::vector<ComponentEntry> queue;
			return queue;
		}

		void ProcessPending() {
			for (auto& e : Pending())
				m_entries.push_back(std::move(e));
			Pending().clear();
		}


		void Register(ComponentEntry entry) {
			m_entries.push_back(std::move(entry));
		}


		const std::vector<ComponentEntry>& GetAll() const { return m_entries; }
	

	private:
		std::vector<ComponentEntry> m_entries;

	};


	namespace detail {

		template<typename T>
		struct AutoRegister {
			AutoRegister(const char* name) {
				ComponentRegistry::Pending().push_back({
					name,
					// hasComponent
					[](Entity e) {
						return Engine.GetECS().Has<T>(e);
					},
					// inspect - ImReflect handles the UI automatically
					[](Entity e) {
						auto& c = Engine.GetECS().Get<T>(e);
						ImReflect::Input("##comp", c);
					},
					// save - nlohmann to_json generated by CHAD_COMPONENT
					[](Entity e, nlohmann::json& j) {
						if (auto* c = Engine.GetECS().TryGet<T>(e))
							j = *c;
					},
					// load - nlohmann from_json generated by CHAD_COMPONENT
					[](Entity e, const nlohmann::json& j) {
						auto& c = Engine.GetECS().CreateComponent<T>(e);
						j.get_to(c);
					}
					});
			}
		};

	}
}


#define CHAD_COMPONENT(Type, ...) \
    IMGUI_REFLECT(Type, __VA_ARGS__) \
    NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Type, __VA_ARGS__) \
    namespace { \
        static ChadEngine::detail::AutoRegister<Type> _ChadAutoReg_##Type { #Type }; \
    }